### ISSUE TITLE
I'm curious to hear why you aren't using the pg native bindings?

### ISSUE THREAD

**Issue by devnetics** [martijndeh/fire#8]
Hey there. I am currently reviewing your implementation, and I'm mainly just curious as to why you are not using the pg.native bindings? See the "Native Bindings" section here: https://github.com/brianc/node-postgres for more details.

**Comment by martijndeh** [comment]
Hi! I haven't seen an immediate need to implement the native bindings yet. I'm running a couple of projects in production without the native bindings and I have no performance issues whatsoever (as long as indices are configured correctly of course).

They do claim a speed improvement of 20%-30%. This seems worth testing. It looks like it does add an extra dependencies which could make the on-boarding more difficult. I'm actually trying to remove some dependencies, like bower, to ease the on-boarding (have a look at the develop branch).

Would you advise on using the native bindings instead and what do you thinking of the extra dependency?

**Comment by kinetics** [comment]
It seems like it's worth testing. 

The two main differences in the code are https://github.com/brianc/node-postgres/issues/762 (unconfirmed) and https://github.com/brianc/node-postgres/issues/736 (confirmed).

For the dependency, in order to install pg-native, there first has to be a check/test that runs to confirm that the postgres client and libraries are already installed on the system. The author suggests just checking for ```pg_config``` to be in the PATH. We could add this to a preinstall script in npm.

I completely agree on removing dependencies, especially ones like bower or grunt or gulp. I prefer to see 100% use of npm (+package.json scripts), as this keeps the project a lot simpler. 

Hope that helps.

**Comment by martijndeh** [comment]
This issue is not relevant anymore. Please have a look at the new version.
